site_name: 幻形者诅咒 Wiki文档
nav:
    - Home: index.md
    - 创建自定义形态:
        - 概览: guides/custom_forms/overview.md
        - 资源包/数据包示例: guides/custom_forms/pack_example.md
        - 基于OriginFur数据驱动方式的自定义模型: guides/data/originfur_resource_pack.md
        - 基于Origins数据驱动方式的自定义形态能力: guides/data/origins_data_pack.md
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - autorefs
  - alias
  - categories
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
    - toc:
        separator: "_"
    - admonition
    
