site_name: 幻形者诅咒 Wiki文档
nav:
    - Home: index.md
    - 中文版介绍页面: overview_page/overview_zh_cn.md
    - 版本:
        - 版本更新日志: update_log/update_log.md
    - Mod内容指南: 
        - 一句话玩法: mod_content/brief_introduction.md
        - 开启模组内容: mod_content/enable_mod_content.md
        - 形态变化效果: mod_content/transform_status_effect.md
        - 形态种类: mod_content/form_types.md
        - 形态的变化与复原指南: mod_content/form_change_and_recovery.md
        - 可用指令: mod_content/commands.md
        - 可用配置项: mod_content/mod_config.md
        - 常见问题: mod_content/common_issues.md
    - 创建自定义形态: 
        - 概览: custom_forms/overview.md
        - 资源包/数据包示例: custom_forms/pack_example.md
        - 基于Origin Furs数据驱动方式的自定义模型: custom_forms/originfur_resource_pack.md
        - 基于Origins数据驱动方式的自定义形态能力: custom_forms/origins_data_pack.md
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - autorefs
  - alias
  - categories
markdown_extensions:
    - toc:
        separator: "_"
    - admonition
    
